In [4]:
import pandas as pd

In [13]:
data = {
    "Name": ["A","B","C"],
    "Sales":[100,200,150]
}

df = pd.DataFrame(data)
df

  Name  Sales
0    A    100
1    B    200
2    C    150

In [14]:
df.to_csv("friends")

In [6]:
data2 = {
    "names":["Mohan","Rohan","Johan","Sohan"],
    "Salary":[90000,80000,70000,90]
}
table = pd.DataFrame(data2)
table

   names  Salary
0  Mohan   90000
1  Rohan   80000
2  Johan   70000
3  Sohan      90

In [7]:
table.to_csv('file1',index=False)

In [9]:
table.describe()

             Salary
count      4.000000
mean   60022.500000
std    40780.739224
min       90.000000
25%    52522.500000
50%    75000.000000
75%    82500.000000
max    90000.000000

In [10]:
table.name("calories")

AttributeError: 'DataFrame' object has no attribute 'name'

In [11]:
data2.name=("calories")

AttributeError: 'dict' object has no attribute 'name' and no __dict__ for setting new attributes

In [12]:
data2.name = "calories"

AttributeError: 'dict' object has no attribute 'name' and no __dict__ for setting new attributes

In [14]:
str = ([1,2,3,5,6,7])
new = pd.Series(str)
new

0    1
1    2
2    3
3    5
4    6
5    7
dtype: int64

In [15]:
str.name = "numbers"

AttributeError: 'list' object has no attribute 'name' and no __dict__ for setting new attributes

In [16]:
data = {
     "Customer_ID": [101,102,103,104,105,106,107,108],
    "Customer_Name": ["Mohan","Rohan","Sohan","Aman","Karan","Neha","Priya","Rahul"],
    "City": ["Delhi","Mumbai","Delhi","Bangalore","Mumbai","Delhi","Bangalore","Mumbai"],
    "Product": ["Laptop","Phone","Tablet","Laptop","Phone","Tablet","Laptop","Phone"],
    "Sales": [55000,20000,15000,60000,22000,14000,58000,21000],
    "Profit": [8000,3000,2000,9000,3200,1800,8500,3100],
    "Quantity": [2,5,3,1,4,2,2,6],
    "Order_Date": [
        "2024-01-10","2024-01-12","2024-01-15","2024-02-01",
        "2024-02-05","2024-02-10","2024-03-02","2024-03-08"
    ]
}

df = pd.DataFrame(data)
df

,Customer_ID,Customer_Name,City,Product,Sales,Profit,Quantity,Order_Date
0,101,Mohan,Delhi,Laptop,55000,8000,2,2024-01-10
1,102,Rohan,Mumbai,Phone,20000,3000,5,2024-01-12
2,103,Sohan,Delhi,Tablet,15000,2000,3,2024-01-15
3,104,Aman,Bangalore,Laptop,60000,9000,1,2024-02-01
4,105,Karan,Mumbai,Phone,22000,3200,4,2024-02-05
5,106,Neha,Delhi,Tablet,14000,1800,2,2024-02-10
6,107,Priya,Bangalore,Laptop,58000,8500,2,2024-03-02
7,108,Rahul,Mumbai,Phone,21000,3100,6,2024-03-08

In [19]:
df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Customer_ID    8 non-null      int64
 1   Customer_Name  8 non-null      object
 2   City           8 non-null      object
 3   Product        8 non-null      object
 4   Sales          8 non-null      int64
 5   Profit         8 non-null      int64
 6   Quantity       8 non-null      int64
 7   Order_Date     8 non-null      object
dtypes: int64(4), object(4)
memory usage: 644.0+ bytes

       Customer_ID         Sales       Profit  Quantity
count      8.00000      8.000000     8.000000  8.000000
mean     104.50000  33125.000000  4825.000000  3.125000
std        2.44949  20552.632782  3095.965116  1.726888
min      101.00000  14000.000000  1800.000000  1.000000
25%      102.75000  18750.000000  2750.000000  2.000000
50%      104.50000  21500.000000  3150.000000  2.500000
75%      106.25000  55750.000000  8125.000000  4.250000
max      108.00000  60000.000000  9000.000000  6.000000